# Generated by Django 5.0.1 on 2024-01-31 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedoedPJ', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/'),
        ),
    ]
